Add an until loop to retry cache invalidation, with exponential backoff
envato/aws-cloudfront-invalidation-buildkite-plugin pull request #3
Opened 2022-02-18 06:53 UTC by aweraw

Subsequent to a couple of reports of issues on buildkite pipelines, this change should prevent broken builds resulting from failed cloudfront invalidation requests.

2022-02-21 02:35 UTC, patrobinson requested changes
This will retry forever even on unexpected errors such as incorrect credentials.

I suggest we at least put an upper bounds on retries. It would be great if we could parse the error code to determine if this is a retriable error, but I appreciate that may not be feasible

2022-02-21 02:39 UTC, aweraw commented
> This will retry forever even on unexpected errors such as incorrect credentials.

Ahh yes, that's definitely a scenario where is shouldn't retry

2022-02-21 04:51 UTC, owenbutler commented
Would it benefit us to print out the error message in the case of failure, so we can debug if it does fail often?  (or infinite loop)?

2022-02-22 01:06 UTC, aweraw commented
> Would it benefit us to print out the error message in the case of failure, so we can debug if it does fail often? (or infinite loop)?

The output from the aws calls should be going to stdout, so we should see them

2022-02-22 22:50 UTC, patrobinson reviewed
A question, but looks better now

2022-02-22 22:50 UTC, patrobinson commented on hooks/post-command
> +fi
I'm not sure this adds any value, we will almost always have credentials, but those credentials may or may not have permission to call `create-invalidation`

2022-03-18 03:42 UTC, patrobinson approved these changes

2022-03-18 04:00 UTC, merged